# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'control_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(768, 506)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.state_1 = QtWidgets.QPushButton(self.centralwidget)
        self.state_1.setGeometry(QtCore.QRect(110, 260, 101, 51))
        self.state_1.setStyleSheet("background-color: rgb(153, 193, 241);")
        self.state_1.setObjectName("state_1")
        self.state_2 = QtWidgets.QPushButton(self.centralwidget)
        self.state_2.setGeometry(QtCore.QRect(240, 260, 101, 51))
        self.state_2.setStyleSheet("background-color: rgb(143, 240, 164);")
        self.state_2.setObjectName("state_2")
        self.state_3 = QtWidgets.QPushButton(self.centralwidget)
        self.state_3.setGeometry(QtCore.QRect(370, 260, 101, 51))
        self.state_3.setStyleSheet("background-color: rgb(87, 227, 137);")
        self.state_3.setObjectName("state_3")
        self.state_4 = QtWidgets.QPushButton(self.centralwidget)
        self.state_4.setGeometry(QtCore.QRect(500, 260, 91, 51))
        self.state_4.setStyleSheet("background-color: rgb(231, 186, 186);")
        self.state_4.setObjectName("state_4")
        self.resume_button = QtWidgets.QPushButton(self.centralwidget)
        self.resume_button.setGeometry(QtCore.QRect(240, 350, 101, 51))
        self.resume_button.setStyleSheet("background-color: rgb(179, 255, 179);")
        self.resume_button.setObjectName("resume_button")
        self.stop_button = QtWidgets.QPushButton(self.centralwidget)
        self.stop_button.setGeometry(QtCore.QRect(390, 350, 101, 51))
        self.stop_button.setStyleSheet("background-color: rgb(255, 179, 179);")
        self.stop_button.setObjectName("stop_button")
        self.lable_app = QtWidgets.QLabel(self.centralwidget)
        self.lable_app.setGeometry(QtCore.QRect(140, 70, 511, 81))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.lable_app.setFont(font)
        self.lable_app.setStyleSheet("background-color: rgb(249, 240, 107);")
        self.lable_app.setAlignment(QtCore.Qt.AlignCenter)
        self.lable_app.setObjectName("lable_app")
        self.control_v = QtWidgets.QPushButton(self.centralwidget)
        self.control_v.setGeometry(QtCore.QRect(620, 260, 111, 51))
        self.control_v.setStyleSheet("background-color: rgb(231, 186, 186);")
        self.control_v.setObjectName("control_v")
        self.lbl_state_now = QtWidgets.QLabel(self.centralwidget)
        self.lbl_state_now.setGeometry(QtCore.QRect(80, 180, 131, 41))
        self.lbl_state_now.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 255, 255);\n"
"border-radius:10px;")
        self.lbl_state_now.setText("")
        self.lbl_state_now.setObjectName("lbl_state_now")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 768, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.state_1.setText(_translate("MainWindow", "Trạng thái 1"))
        self.state_2.setText(_translate("MainWindow", "Trạng thái 2"))
        self.state_3.setText(_translate("MainWindow", "Trạng thái 3"))
        self.state_4.setText(_translate("MainWindow", "Trạng thái 4"))
        self.resume_button.setText(_translate("MainWindow", "Tiếp tục"))
        self.stop_button.setText(_translate("MainWindow", "Dừng"))
        self.lable_app.setText(_translate("MainWindow", "App điều khiển trạng thái"))
        self.control_v.setText(_translate("MainWindow", "Điều khiển vận tốc"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
